Update const generation scripts based on zwave-js 13
home-assistant-libs/zwave-js-server-python pull request #1079
Opened 2024-10-03 00:22 UTC by raman325

2024-10-03 06:27 UTC, MartinHjelmare requested changes

2024-10-03 06:27 UTC, MartinHjelmare commented on zwave_js_server/const/command_class/notification.py
> +    MODE_ENABLED = 597
Is this correct?

2024-10-03 14:21 UTC, raman325 commented on zwave_js_server/const/command_class/notification.py
> +    MODE_ENABLED = 597
no, good catch

2024-10-03 14:46 UTC, MartinHjelmare commented on scripts/generate_multilevel_sensor_constants.py
> +for sensor_props in pathlib.Path("sensors.json").read_text():
We still need to load the json to native types.

2024-10-04 05:54 UTC, MartinHjelmare approved these changes
Thanks!

2024-10-04 05:54 UTC, merged