Handle maybe not known responses
home-assistant-libs/zwave-js-server-python pull request #743
Opened 2023-09-04 00:43 UTC by raman325

We have to assume that the response could be undefined, in which case the key wouldn't be in the deserialized dict because typescript does not serialize undefined

2023-09-04 03:46 UTC, MartinHjelmare requested changes

2023-09-04 03:46 UTC, MartinHjelmare commented on zwave_js_server/model/node/__init__.py
>          assert data
This will still raise if `data` is empty.

2023-09-04 04:13 UTC, MartinHjelmare commented
There are also two keys in the node state that have MaybeNotKnown types in the server. Do we handle those correctly here in the client?

2023-09-04 04:26 UTC, raman325 commented
> There are also two keys, isSecure and lastSeen, in the node state that have MaybeNotKnown types in the server. Do we handle those correctly here in the client?

fixed `isSecure`, `lastSeen` was already handled correctly

2023-09-04 04:43 UTC, MartinHjelmare reviewed
Is the fixture `is_secure_unknown` incorrect? Maybe update it or remove it?

Can we add tests for the new uncovered cases?

2023-09-04 14:02 UTC, MartinHjelmare approved these changes
Change looks good! Just the comments on the tests remaining, which are not critical.

2023-09-05 01:45 UTC, raman325 commented
> Is the fixture `is_secure_unknown` incorrect? Maybe update it or remove it?
> 
> Can we add tests for the new uncovered cases?

Updated fixture name - for the uncovered paths, I can fake it but I don't have any real dumps that would result in this case. Do you think it's worth manipulating existing state fixtures to achieve the same thing?

2023-09-05 01:52 UTC, merged

2023-09-05 01:52 UTC, raman325 commented
let me know your thoughts, I will submit a second PR for tests if needed

2023-09-05 05:31 UTC, MartinHjelmare commented
I think it would be good to test it. We can adjust the node data before creating the node or similar.